### ISSUE TITLE
Review the labels, description/help, default values, etc. from UI of Liberty on AKS offer

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.liberty.aro#17]
[Content review for Liberty on AKS UI.docx](https://github.com/WASdev/azure.liberty.aro/files/7158259/Content.review.for.Liberty.on.AKS.UI.docx)

The source code including all of text is here: [createUiDefinition.json](https://github.com/majguo/azure.liberty.aks/blob/master/src/main/arm/createUiDefinition.json)

To facilitate the review, reviewers can preview the changes using the **Create UI Definition Sandbox**:
- Open [Create UI Definition Sandbox](https://portal.azure.com/?feature.customPortal=false#blade/Microsoft_Azure_CreateUIDef/SandboxBlade) in a new tab of browser;
- Open source code [createUiDefinition.json](https://github.com/majguo/azure.liberty.aks/blob/master/src/main/arm/createUiDefinition.json) in a new tab of browser;
- Replace the content of work area in **Create UI Definition Sandbox** with the content of **source code `createUiDefinition.json`**;
- Click **Preview** at the left-bottom of **Create UI Definition Sandbox**;

or open the [preview link](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20191212-arm-rhel-was-nd-v9-cluster-previewazure-liberty-aks) of the testing offer if you can access subscription "Azure WebSphere Collaboration Sponsorship".

**Comment by majguo** [comment]
Hello @helyarp @git4rk , could you pls help review the content for Liberty on AKS offer? Thanks.

**Comment by helyarp** [comment]
@majguo Hi, I don't have suggested changes. @git4rk Ranjan, should the sentence "The size of the virtual machines **that will form** the nodes in the cluster." be changed to "The size of the virtual machines **for** the nodes in the cluster. This cannot be changed after creating the cluster."?

**Comment by majguo** [comment]
@helyarp Hello Pam, I vote for plural as all virtual machines have the same size specified by the user.

**Comment by git4rk** [comment]
@helyarp @majguo I think "for the nodes in the cluster." sounds good.

**Comment by majguo** [comment]
OK, so the final version of the sentence will be: "The size of the virtual machines for the nodes in the cluster."
