### ISSUE TITLE
Deployment failed "PrincipalNotFound"

### ISSUE THREAD

**Issue by m-reza-rahman** [WASdev/azure.liberty.aro#59]
Simple deployment without an application randomly fails:

{

"status": "Failed",

"error": {

"code": "PrincipalNotFound",

"message": "Principal c936aacc547d4cdbbbb73e31fba068e7 does not exist in the directory 9ef060d3-1c7d-47f0-ae5e-3be36d7ba188."

}

}

**Comment by majguo** [comment]
It looks like the random failure is caused by the timing issue, which means the service principal is created asynchronously, see https://stackoverflow.com/questions/35172941/azuread-powershell-new-azurermroleassignment-keeps-failing.

**Comment by majguo** [comment]
I also asked question in Microsoft internal StackOverflow: https://stackoverflow.microsoft.com/questions/299178.

**Comment by majguo** [comment]
When I verified the new release after rolling out https://github.com/WASdev/azure.liberty.aro/pull/78, the deployment failed with the following error messages:
```
{
      "code": "InvalidPrincipalId",
      "message": "A valid principal ID must be provided for role assignment."
}
```
I think the root cause is similar that the service principal is created asynchronously, and we need to wait a while until it's available.
