### ISSUE TITLE
Review the labels, description/help, default values, etc. from UI

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.liberty.aro#6]
[Content review for Liberty on ARO UI.docx](https://github.com/WASdev/azure.liberty.aro/files/7030986/Content.review.for.Liberty.on.ARO.UI.docx)

The source code including all of text is here: [createUiDefinition.json](https://github.com/WASdev/azure.liberty.aro/blob/main/src/main/arm/createUiDefinition.json)

@git4rk The content review doc is uploaded as above. Pls assign the issue to the focal from IBM documentation team and start review at earliest convenience. If there is any confusion about the doc, here is the [preview link](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20191212-arm-rhel-was-nd-v9-cluster-previewazure-liberty-aro) that can be used as a live demo.

**Comment by majguo** [comment]
@helyarp @git4rk Thanks for your review. I suppose review is done and it's ready to apply your suggestions, correct?

**Comment by helyarp** [comment]
@majguo On my end, the review is done. @git4rk Do you agree?

**Comment by git4rk** [comment]
@majguo yes, pls go ahead and apply the suggestions and let us know if you have any questions. Thanks

**Comment by majguo** [comment]
Hello @helyarp , here is my response for one of your questions in the review doc:

> NEED INFO: The Azure doc tells users to copy the client secret when they register an application: https://docs.microsoft.com/en-us/azure/digital-twins/how-to-create-app-registration-portal#collect-client-secret
The doc says to copy the Secret ID and Value from the Certificates & secrets pane of the App registrations page. Can the user use the Value that was copied when registering the app for Client secret? Or must the user create a new client secret and copy the value that it mentions in https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app?WT.mc_id=Portal-fx#add-a-client-secret?

I looked at both documentations and both of them ask user to create a new secret by selecting "Certificates & secrets > New client secret", before copying secret value. So I suggest using the original text/link with your recommended revision.

**Comment by majguo** [comment]
Hello @git4rk , here is my response for your review comment:

> Change "User assigned managed identity" to "User-assigned managed identity"

Good catch. However, the text comes from the standard component "Microsoft.ManagedIdentity.IdentitySelector", which is not customizable. If you search it from the source code "createUiDefinition.json", you won't find it.
