### ISSUE TITLE
Update Operator version to 1.2.0

### ISSUE THREAD

**Issue by venunathb** [WASdev/azure.liberty.aro#91]

**Comment by majguo** [comment]
@venunathb @git4rk @edburns 
From the description of 1.2.0 in https://github.com/OpenLiberty/open-liberty-operator/releases:
```
Pending validation and official release. Do not use it in production.
```
![image](https://user-images.githubusercontent.com/10357495/236126602-14cbbfee-bd3d-4160-a709-98d2b386fb3f.png)

I think we should wait until it's recommended for production?

**Comment by majguo** [comment]
Also, there is no relative [release](https://github.com/OpenLiberty/open-liberty-operator/tree/main/deploy/releases) directory including installation scripts for 1.2.0 yet:
![image](https://user-images.githubusercontent.com/10357495/236127095-73c1fae0-5f86-4ee8-844b-37bc5fa77123.png)

**Comment by majguo** [comment]
@git4rk You're right, it belongs to aks repo. The latest version of OLO & WLO will be automatically installed with OLM for aro repo.

**Comment by edburns** [comment]
It seems to me this issue should be closed, no?

**Comment by majguo** [comment]
@edburns I realized that the similar changes from WASdev/azure.liberty.aks/pull/83 are also needed for `azure.liberty.aro` repo, I'll look into it next week, and let's keep this issue open as for now.
